[project]
name = "brokest"
version = "0.0.1"
description = "More broke than a broker"
authors = [
    {name = "RenChu Wang",email = "patrick1031wang@gmail.com"}
]
license = {text = "GPL"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
autoflake = "^2.3.1"
black = "^25.1.0"
isort = "^6.0.1"
