[project]
name = "brokest"
version = "0.0.0"
description = "More broke than a broker"
authors = [
    {name = "RenChu Wang",email = "patrick1031wang@gmail.com"}
]
license = {text = "GPL"}
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "freqtrade (>=2025.3,<2026.0)",
    "numpy",
    "pandas (>=2.2.3,<3.0.0)",
    "scipy (>=1.15.2,<2.0.0)",
    "torch (>=2.6.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
autoflake = "^2.3.1"
black = "^25.1.0"
isort = "^6.0.1"
pre-commit = "^4.2.0"

[tool.poetry.group.build.dependencies]
build = "^1.2.2.post1"
cython = "^3.0.12"

[tool.poetry.group.tests.dependencies]
pytest = "^8.3.5"
pytest-cov = "^6.1.1"
pytest-xdist = "^3.6.1"
pytest-sugar = "^1.0.0"
