name: Pre Commit Checks
on: [push]
jobs:
  format:
    name: 📑 Formatting
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3

      - name: 🐍 Install conda
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: env.yaml
          cache-environment: true
          post-cleanup: all
          create-args: >-
            python=3.12
          init-shell: >-
            bash
            powershell

      - name: ⬇️ Python Pip
        run: pip install -e '.[extras]'

      - name: 🏃 autoflake
        run: pre-commit run --all-files autoflake

      - name: 🏃 isort
        run: pre-commit run --all-files isort

      - name: 🏃 black
        run: pre-commit run --all-files black

  type:
    name: 👨‍⚕️ Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3

      - name: 🏗️ python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: ⬇️ Python Pip
        run: pip install -e '.[extras]'

      - name: 📦 Install type stubs
        run: mypy . --install-types --non-interactive

      - name: 🏃 mypy
        run: pre-commit run --all-files black
