name: Publish
on:
  push:
    tags:
      - v*

jobs:
  pypi-publish:
    name: ⬆️ Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3

      - name: 🐍 Install conda
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: env.yaml
          cache-environment: true
          post-cleanup: all
          create-args: >-
            python=3.12
          init-shell: >-
            bash
            powershell

      - name: ⬇️ Python Pip
        run: pip install -e '.[dev]'

      - name: 🪶 Build
        run: python -m build

      - name: 📰 Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
