name: Unit Testing
on: [push]
jobs:
  unit-test:
    name: 🧪 Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3

      - name: 🐍 Install conda
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: env.yaml
          cache-environment: true
          post-cleanup: all
          create-args: >-
            python=3.12
          init-shell: >-
            bash
            powershell

      - name: ⬇️ Python Pip
        run: pip install -e '.[dev]'

      - name: 🏃 pytest
        run: pytest -xv
