name: Unit Testing
on: [push]
jobs:
  unit-test:
    name: 🧪 Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3

      - name: 🏗️ python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: ⬇️ Python Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.2
          installer-parallel: true

      - name: ⬇️ TA-Lib
        run: git clone https://github.com/TA-Lib/ta-lib && cd ta-lib && sudo ./install

      - name: ⬇️ Python Dependencies
        run: poetry install

      - name: 🏃 pytest
        run: poetry run pytest -xv
